#!/usr/bin/env python3
"""source/passages.txt -> data/passages.js

Every excerpt is verified to appear verbatim on the page it cites, and gets a
cleaned variant so it still matches the page in Cleaned reading mode.
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fixes as fixlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "source", "passages.txt")
ENT = os.path.join(ROOT, "data", "entries.js")
OUT = os.path.join(ROOT, "data", "passages.js")

TAGS = {
    "craft":    "The writing",
    "turning":  "Turning point",
    "thread":   "A running thread",
    "gut":      "Gut punch",
    "thinking": "Thinking it through",
}


def load_pages():
    with open(ENT, encoding="utf-8") as fh:
        s = fh.read()
    payload = json.loads(s[s.index("=") + 1:].rstrip().rstrip(";"))
    out = {}
    for e in payload["entries"]:
        text = " ".join(b["x"] for b in e["blocks"] if b["t"] == "p")
        out[e["id"]] = {"text": " ".join(text.split()), "n": e["n"],
                        "pretty": e["pretty"], "title": e["title"], "ch": e["ch"]}
    return out


def main():
    pages = load_pages()
    rules = fixlib.load_rules()
    with open(SRC, encoding="utf-8") as fh:
        raw = fh.read()

    items, errors = [], []
    cur, buf = None, []

    def flush():
        text = " ".join(" ".join(buf).split())
        buf.clear()
        if text and cur is not None:
            cur["note"].append(text)

    for lineno, line in enumerate(raw.split("\n"), 1):
        st = line.strip()
        if st.startswith("#"):
            continue
        if st.startswith("@@"):
            flush()
            if cur:
                items.append(cur)
            meta = {}
            for part in st[2:].split("|"):
                if "=" in part:
                    k, v = part.split("=", 1)
                    meta[k.strip()] = v.strip()
            pid = meta.get("page", "")
            if pid not in pages:
                errors.append("line %d: unknown page %r" % (lineno, pid))
            tag = meta.get("tag", "craft")
            if tag not in TAGS:
                errors.append("line %d: unknown tag %r" % (lineno, tag))
            cur = {"page": pid, "tag": tag, "title": meta.get("title", ""),
                   "quotes": [], "note": []}
            continue
        if cur is None:
            continue
        if st.startswith(">"):
            flush()
            q = st[1:].strip()
            if cur["page"] in pages and " ".join(q.split()) not in pages[cur["page"]]["text"]:
                errors.append("line %d: not on %s: %r" % (lineno, cur["page"], q[:64]))
                continue
            entry = {"x": q}
            c = fixlib.apply(q, rules)
            if c != q:
                entry["c"] = c
            cur["quotes"].append(entry)
            continue
        if not st:
            flush()
            continue
        buf.append(st)

    flush()
    if cur:
        items.append(cur)

    if errors:
        print("PASSAGE CHECK FAILED:")
        for e in errors:
            print("  " + e)
        sys.exit(1)

    for it in items:
        p = pages[it["page"]]
        it["n"], it["pretty"], it["ptitle"] = p["n"], p["pretty"], p["title"]

    items.sort(key=lambda i: i["n"])

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by tools/build_passages.py from source/passages.txt.\n")
        fh.write("window.PASSAGES = ")
        json.dump({"items": items, "tags": TAGS}, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")

    print("wrote %s" % OUT)
    print("  %d passages, %d verified excerpts"
          % (len(items), sum(len(i["quotes"]) for i in items)))


if __name__ == "__main__":
    main()
