#!/usr/bin/env python3
"""Turn source/questions.txt into data/questions.js.

Every pull quote is verified to appear verbatim in the page it cites.
Run:  python3 tools/build_questions.py
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fixes as fixlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "source", "questions.txt")
ENT = os.path.join(ROOT, "data", "entries.js")
OUT = os.path.join(ROOT, "data", "questions.js")
RULES = []


def load_entries():
    with open(ENT, encoding="utf-8") as fh:
        s = fh.read()
    payload = json.loads(s[s.index("=") + 1:].rstrip().rstrip(";"))
    pages = {}
    for e in payload["entries"]:
        text = " ".join(b["x"] for b in e["blocks"] if b["t"] == "p")
        pages[e["id"]] = {"text": " ".join(text.split()), "title": e["title"]}
    return pages


def slug(text, used):
    base = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:48].rstrip("-")
    s = base
    i = 2
    while s in used:
        s = "%s-%d" % (base, i)
        i += 1
    used.add(s)
    return s


def main():
    global RULES
    RULES = fixlib.load_rules()
    pages = load_entries()
    with open(SRC, encoding="utf-8") as fh:
        raw = fh.read()

    questions = []
    cats = []
    cat = None
    cur = None
    buf = []
    used = set()
    errors = []

    def flush_para():
        text = " ".join(" ".join(buf).split())
        buf.clear()
        if text and cur is not None:
            cur["a"].append(text)

    for lineno, line in enumerate(raw.split("\n"), 1):
        stripped = line.strip()
        if stripped.startswith("#") and not stripped.startswith("##"):
            continue
        if stripped.startswith("## cat="):
            flush_para()
            cat = stripped[len("## cat="):].strip()
            if cat not in cats:
                cats.append(cat)
            continue
        if stripped.startswith("??"):
            flush_para()
            if cur is not None:
                questions.append(cur)
            q = stripped[2:].strip()
            cur = {"id": slug(q, used), "cat": cat, "q": q, "a": [],
                   "pulls": [], "cites": []}
            continue
        if cur is None:
            continue
        if stripped.startswith(">"):
            flush_para()
            body = stripped[1:].strip()
            if "|" not in body:
                errors.append("line %d: pull quote missing |" % lineno)
                continue
            pid, quote = body.split("|", 1)
            pid, quote = pid.strip(), quote.strip()
            if pid not in pages:
                errors.append("line %d: unknown page %s" % (lineno, pid))
                continue
            norm = " ".join(quote.split())
            if norm not in pages[pid]["text"]:
                errors.append("line %d: quote not found on %s: %r"
                              % (lineno, pid, norm[:70]))
                continue
            pull = {"p": pid, "x": quote}
            cleaned = fixlib.apply(quote, RULES)
            if cleaned != quote:
                pull["c"] = cleaned          # matches the page in Cleaned mode
            cur["pulls"].append(pull)
            if pid not in cur["cites"]:
                cur["cites"].append(pid)
            continue
        if stripped.startswith("+"):
            flush_para()
            for pid in stripped[1:].split():
                if pid not in pages:
                    errors.append("line %d: unknown page %s" % (lineno, pid))
                elif pid not in cur["cites"]:
                    cur["cites"].append(pid)
            continue
        if not stripped:
            flush_para()
            continue
        buf.append(stripped)

    flush_para()
    if cur is not None:
        questions.append(cur)

    if errors:
        print("QUOTE CHECK FAILED:")
        for e in errors:
            print("  " + e)
        sys.exit(1)

    for q in questions:
        if not q["a"]:
            print("warning: no answer for %r" % q["q"])

    payload = {"questions": questions, "cats": cats}
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by tools/build_questions.py from source/questions.txt.\n")
        fh.write("window.QUESTIONS = ")
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")

    pulls = sum(len(q["pulls"]) for q in questions)
    print("wrote %s" % OUT)
    print("  %d questions in %d categories, %d verified quotes"
          % (len(questions), len(cats), pulls))


if __name__ == "__main__":
    main()
